### ISSUE TITLE
Missing community calls notes and video for September 2nd

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/community#111]

**Comment by leogr** [comment]
I have noticed the notes are still here https://hackmd.io/6sEAlInlSaGnLz2FnFz21A 
/assign @kris-nova 
/kind bug

**Comment by leogr** [comment]
Added here :point_right: https://github.com/falcosecurity/community/blob/master/meeting-notes/2020-08-12-to-2020-12-16.md#2020-09-02
