### ISSUE TITLE
teal-logo.png might be broken?

### ISSUE THREAD

**Issue by distortedsignal** [falcosecurity/community#133]
I'm making a presentation to introduce Falco to my company, and I wanted to embed official logos into the presentation. I cloned this repo and tried to insert all the images under the `logo` directory. The "primary logo" and "white logo" worked perfectly, but the "teal logo" showed a broken image. When I attempted to view the image in Firefox (by navigating to `file://Path/to/teal-logo.png`), I got the following error:

<img width="1272" alt="Screen Shot 2021-03-03 at 10 20 07 AM" src="https://user-images.githubusercontent.com/2186874/109853939-5061c000-7c0b-11eb-8c1c-9e0c2063dc78.png">

I'm going to try to embed the current version of the logo below:

![Maybe Broken Image](https://github.com/falcosecurity/community/blob/3503c220b938e83c99f00f93950bf48a47cb40a6/logo/teal-logo.png)

Do you want to change this to be a symlink to the primary logo?

**Comment by leodido** [comment]
You're right, it's an SVG, not a PNG! I'll fix it right now, thanks for noticing :)

In the meantime, you can find the logos also [here](https://github.com/falcosecurity/falco/tree/master/brand).

**Comment by distortedsignal** [comment]
Thanks man - I was really confused about why it was broken.

Sorry about the `kind` annotation confustion - I wasn't sure what it needed to be in order to get to the correct person. It might be helpful if the bot listed the available `kind`s when asking for a kind? Just a thought - I don't expect it go anywhere.

**Comment by Issif** [comment]
The CNCF hosts some images too [here](https://github.com/cncf/artwork/blob/master/examples/incubating.md#falco-logos) as Falco is incubated
