### ISSUE TITLE
Falco project meeting @ KC+CNC NA 2022

### ISSUE THREAD

**Issue by jsalinas32** [falcosecurity/community#155]
Hey team - 
Opening an issue about the upcoming opportunities at Kubecon+CloudNativeCon NA 2022 in Detroit, MI. 
This ticket is to kick off planning for the project meeting happening Oct. 25, 2022 @ xx:xx.

Falco project meeting (4 hrs)

Next steps: 
- [x] start planning async 
- [x] weekly updates at our community call on progress
- [x] maintainers - who would like to help plan and speak at project meeting? 
- [x] community - attendance of who is at Kubecon and can support project meeting? 

What are the topics we should discuss at the meeting?  
- [x] submit suggestions here: https://hackmd.io/@xvgwkoKqQDW71f8gXOibKw/rk9fL3vxj 

How should we structure the agenda? 
- [x] agenda design: https://docs.google.com/document/d/1dR7YjXC9D35aQ2mbqdq0UPB_ir70gYUJOHVI3vh1Yik/edit?usp=sharing 
- [ ] who is the final approver for the project agenda? 

What other items do we need to coordinate: 
- [ ] food/drink
- [x] swag
- [ ] presentation
- [x] invitation to the community (email)
- [x] invitation to the community (twitter)
- [x] invitation to the community (slack)

**Comment by leogr** [comment]
Done!

:partying_face: 

/close
