### ISSUE TITLE
Falco materials for Kubecon NA 2022

### ISSUE THREAD

**Issue by jsalinas32** [falcosecurity/community#157]
Hi team - I am creating materials for events that the community can leverage to help evangelize Falco. Please provide feedback and/or edits. 

- Kickstand signL [sign v1](https://www.canva.com/design/DAFNcSUru7s/SHzgRS-8i3gUGSIS0ynckg/edit?utm_content=DAFNcSUru7s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- Postcards, bookmark, or other suggestions
  - [jacque] v1 for Kubecon NA postcard: [Canva - Kubecon postcard](https://www.canva.com/design/DAFNXRyEU5w/KfTItqQ4XqIPrAT45J1g0Q/edit?utm_content=DAFNXRyEU5w&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) 
  - [jacque] v1 for bookmark: [falco bookmark](https://www.canva.com/design/DAFNb4L7_xo/tOwZO18vHDXFmbK7xt-0pg/edit?utm_content=DAFNb4L7_xo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [jacque] v1 postcard w/value props Kubecon: [falco postcard](https://www.canva.com/design/DAFNcFmw3GQ/-BcL9a6ovT_A0vMMWpB8TQ/edit?utm_content=DAFNcFmw3GQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - Stickers
  - [jacque] v1 for stickers: [stacked round white sticker](https://www.canva.com/design/DAFNb6ilYt8/tgqCYCyLYnRG71aceFlF3g/edit?utm_content=DAFNb6ilYt8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [jacque] v1 for stickers: [stacked round teal sticker](https://www.canva.com/design/DAFNcAXko1Y/ZulkKpvW1inEaUV5wwrbzQ/edit?utm_content=DAFNcAXko1Y&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [jacque] v1 for stickers: [landscape logo](https://www.canva.com/design/DAFNcGXvnZQ/3y8HF0r02VC3Pj_4223hKA/edit?utm_content=DAFNcGXvnZQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [jacque] [pull up banner](https://www.canva.com/design/DAFNc_TYogg/qqtAOyKYFZNDZrUUwrECVQ/edit?utm_content=DAFNc_TYogg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [jacque] [table cloth](https://www.canva.com/design/DAFNc0ZkV1I/ICqEUz-IVrSFCN3bHna9zw/edit?utm_content=DAFNc0ZkV1I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by jsalinas32** [comment]
![Falco pullup banner](https://user-images.githubusercontent.com/112978354/194150180-5dbbe305-6bef-4a68-b8d1-3256a98c51b3.png)
Hi team - I need to get these to the printers soon. I've updated the pull up banner. 
Can I get someone to take a look at the image and let me know your feedback?

**Comment by jsalinas32** [comment]
[Falco postcard.pdf](https://github.com/falcosecurity/community/files/9718615/Falco.postcard.pdf)
Please review before I send to printers.

**Comment by jsalinas32** [comment]
![2](https://user-images.githubusercontent.com/112978354/194152201-18c8d01b-43ba-4495-9d3f-7990401ca1d2.jpg)
![1](https://user-images.githubusercontent.com/112978354/194152216-728adb59-95a6-427f-b231-7262540673a5.jpg)

**Comment by jsalinas32** [comment]
![1](https://user-images.githubusercontent.com/112978354/194152426-3dfc0ce8-0923-49c4-95a1-fe9cdfe58fe5.jpg)
![2](https://user-images.githubusercontent.com/112978354/194152444-e61550c5-6ed4-4c69-bda1-100ce955c87a.jpg)

**Comment by jsalinas32** [comment]
![1](https://user-images.githubusercontent.com/112978354/194154776-a5ff8bc3-2ee3-4e70-abb6-fba8da44ead9.png)
![2](https://user-images.githubusercontent.com/112978354/194154778-d1c0c803-3485-4364-807e-7cba3f984803.png)

**Comment by jsalinas32** [comment]
![1](https://user-images.githubusercontent.com/112978354/194154864-4efb6f8d-12eb-42b3-b02a-210e0f76bc2d.png)
![2](https://user-images.githubusercontent.com/112978354/194154867-4bb98878-43f5-45fe-8ac6-0047797719cf.png)

**Comment by jsalinas29** [comment]
@leogr @jasondellaluce let me know if you have any feedback :) 
i need to send to printers soon

**Comment by jsalinas32** [comment]
everything was printed w/the exception of the bookmarks (we will have o'reilly ones)
