### ISSUE TITLE
Falco kiosk at Kubecon NA 22 - call for volunteers

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#159]
Hi team - I need volunteers to help staff the Falco kiosk during Kubecon NA 2022 in Detroit. 

Event dates: 

- Oct. 10/25: set up volunteers from 8am - 5pm
- Oct. 10/26: staffing from 10am - 8pm
- Oct. 10/27: staffing from 10am - 5pm
- Oct. 10/28: staffing & breakdown from 10am - 4pm

[Please sign up here](https://docs.google.com/spreadsheets/d/1PISqNDdOIaMfR4eoDIErOGdOXmEcJKBAhYfVMyzDayI/edit?usp=sharing)

**Comment by leogr** [comment]
Done

/close
