### ISSUE TITLE
Discuss coding conventions, formatters, and their integration in Falco workflow

### ISSUE THREAD

**Issue by leodido** [falcosecurity/community#16]
**What type of proposal is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind issue
> /kind pr

**Details about the discussion**:

- Which coding style to adopt for Falco userspace C++ code?
- Which format for Cmake files?
- Which other formatters do we need (eg., python code for integration tests)?
- How to integrate `clang-format` and `cmake-format` into the GitHub workflow?
- Do we want to provide tools (eg., git presubmit hooks) locally or do we want an automatic job that performs the formatting if missing during PRs?

More [here](https://github.com/falcosecurity/test-infra/issues/47).

**Comment by leodido** [comment]
During the yesterday office hours we started to discuss which coding style conventions to use.

I propose to leave this open until we have all the answers to the above questions.

**Comment by leodido** [comment]
Discussed also in another Office Hours ([meeting minutes](https://github.com/falcosecurity/office-hours/blob/master/meeting-notes/2019-Jul-11.md)).

**Comment by rajibmitra** [comment]
https://github.com/falcosecurity/falco/issues/991
cc @leodido
