### ISSUE TITLE
[NOMINATION] Falco contributor of the month - March

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#164]
Please comment on the issue your nominations for the month of March.
Please include name + link to their contribution.
/kind <documentation>

**Comment by pandyamarut** [comment]
@pandyamarut --> https://github.com/falcosecurity/falcosidekick/pull/396 
--> https://github.com/falcosecurity/falcosidekick/pull/395

**Comment by EXONER4TED** [comment]
Vote: @FedeDP - don't know if you've won one of these yet, but you for sure deserve it.

- https://github.com/falcosecurity/driverkit/pulls?q=is%3Apr+is%3Aclosed+author%3AFedeDP+
- https://github.com/falcosecurity/libs/pulls?q=is%3Apr+is%3Aclosed+author%3AFedeDP+
- https://github.com/falcosecurity/kernel-crawler/pulls?q=is%3Apr+is%3Aclosed+author%3AFedeDP+

**Comment by Andreagit97** [comment]
Vote: @FedeDP  :1st_place_medal:

**Comment by FedeDP** [comment]
I vote @Andreagit97; he is always doing such a tireless job on libs repository, it's stunning really!

**Comment by jsalinas29** [comment]
![falco contributor of the month (3)](https://user-images.githubusercontent.com/54957621/229564372-e7567037-e066-4fb3-8de4-24b5f8e4b1ae.png)
