### ISSUE TITLE
[NOMINATION] Falco contributor of the month - April

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#165]
Please comment on the issue your nominations for the month of April.
Please include name + link to their contribution.
kind/documentation

**Comment by Issif** [comment]
I would like to nominate [@tspearconquest](https://github.com/tspearconquest) for the help he provides on Slack and in GH issues to the users:
* https://kubernetes.slack.com/archives/CMWH3EH32/p1681310995349809?thread_ts=1681310922.272789&cid=CMWH3EH32
* https://kubernetes.slack.com/archives/CMWH3EH32/p1681307956053579?thread_ts=1681305497.799439&cid=CMWH3EH32
* https://kubernetes.slack.com/archives/CMWH3EH32/p1680790262124459?thread_ts=1680530198.737349&cid=CMWH3EH32
* https://kubernetes.slack.com/archives/CMWH3EH32/p1680650817687069?thread_ts=1680645666.546799&cid=CMWH3EH32
* https://github.com/falcosecurity/falco/issues/2487#issuecomment-1505364859
* https://github.com/falcosecurity/charts/pull/314#event-6218869376
* https://github.com/falcosecurity/falco/issues/2462
