### ISSUE TITLE
[NOMINATION] Falco contributor of the month - May 

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#166]
Please comment on the issue your nominations for the month of May.
Please include name + link to their contribution.

kind/documentation

**Comment by Andreagit97** [comment]
I would like to nominate [@jasondellaluce ](https://github.com/jasondellaluce) for the amazing work on plugins and state management:
* https://github.com/falcosecurity/libs/pull/1078
* https://github.com/falcosecurity/libs/pull/1087
* https://github.com/falcosecurity/libs/pull/1094
* https://github.com/falcosecurity/libs/pull/1096

**Comment by jsalinas29** [comment]
![falco contributor of the month (750 × 500 px) (2)](https://github.com/falcosecurity/community/assets/54957621/52d782ff-4818-49d0-8a68-20f8fd37b6c3)
Congrats @jasondellaluce

**Comment by LucaGuerra** [comment]
Great job! 🚀
