### ISSUE TITLE
[NOMINATION] Falco contributor of the month - February

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#174]
Please comment on the issue your nominations for the month of February.
Please include name + link to their contribution.

**Comment by maxgio92** [comment]
@incertum:
- https://github.com/falcosecurity/libs/pulls?q=is%3Apr+is%3Aclosed+author%3Aincertum
- https://github.com/falcosecurity/falco/pulls?q=is%3Apr+is%3Aclosed+author%3Aincertum

**Comment by FedeDP** [comment]
vote: @dwindsor :rocket: 
He has been doing a wonderful job both as a driverkit maintainer and on libs (adding modern bpf syscalls like there is no tomorrow!!!)
* https://github.com/falcosecurity/libs/pull/910
* https://github.com/falcosecurity/libs/pull/909
* https://github.com/falcosecurity/libs/pull/908

And @incertum too! Not only she became a new libs maintainer, but she's continuously helping us everywhere:
* https://github.com/falcosecurity/libs/pull/881
* https://github.com/falcosecurity/libs/pull/880

**Comment by EXONER4TED** [comment]
vote: @dwindsor 💯

**Comment by araujof** [comment]
@incertum

**Comment by jsalinas29** [comment]
Thank you everyone that nominated and voted!
Congratulations to @dwindsor for your contributions in February. You are February's contributor of the month.

**Comment by jsalinas29** [comment]
Thank you everyone that nominated and voted!
Congratulations to @incertum for your contributions in February. You are February's contributor of the month.

**Comment by jsalinas29** [comment]
We had a tie this month! Congratulations to both for your amazing work.
