### ISSUE TITLE
[NOMINATION] Falco contributor of the month - January

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#175]
Please comment on the issue your nominations for the month of January.
Please include name + link to their contribution.

**Comment by maxgio92** [comment]
@EXONER4TED:
- https://github.com/falcosecurity/driverkit/pulls?q=is%3Apr+is%3Aclosed+author%3AEXONER4TED
- https://github.com/falcosecurity/kernel-crawler/pulls?q=is%3Apr+is%3Aclosed+author%3AEXONER4TED

**Comment by Andreagit97** [comment]
Vote: @EXONER4TED :partying_face:

**Comment by FedeDP** [comment]
Agree, vote: @EXONER4TED !

**Comment by leogr** [comment]
Agree too, @EXONER4TED :+1:

**Comment by jsalinas29** [comment]
Thank you everyone that nominated and voted! 
Congratulations to @EXONER4TED for your contributions in January.  You are January's contributor of the month. 
https://github.com/falcosecurity/driverkit/pulls?q=is%3Apr+is%3Aclosed+author%3AEXONER4TED
https://github.com/falcosecurity/kernel-crawler/pulls?q=is%3Apr+is%3Aclosed+author%3AEXONER4TED
