### ISSUE TITLE
Proposal for Kubecon social cards 

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#180]
![falco_teal_v1](https://user-images.githubusercontent.com/54957621/225156971-3d4e798d-f112-4070-8144-f535898e625c.jpg)
![falco_white_v1](https://user-images.githubusercontent.com/54957621/225156993-a9f6aff3-f90a-4071-a5d9-2f19b8c4cc20.jpg)

**Comment by xinity** [comment]
The blue one is cool 👍
For the white one the Falco logo might be a little to hard to be seen in this color

Besides while I'd love this to be obvious, I'm not sure if everyone will be able to identify Falco just with the logo 😊

**Comment by Andreagit97** [comment]
Same here, i love the blue one :)

**Comment by leogr** [comment]
+1 for the blue one

**Comment by jsalinas29** [comment]
hi everyone - if you have more feedback, please comment. Otherwise, we will close this issue. Thanks!
