### ISSUE TITLE
Falco community newsletter - April 

### ISSUE THREAD

**Issue by jsalinas29** [falcosecurity/community#189]
Hey community - provide us with your news, blogs, videos, and or get creative to be included in the April newsletter. 

Please comment on the issue in the following format: 
- name
- title of content
- abstract
- link to content 

To be considered for the April newsletter, please submit your comment by the 24th at the latest. Thanks!

**Comment by incertum** [comment]
Hey 👋 @jsalinas29: @jasondellaluce @FedeDP, @Andreagit97 and myself would like to write up a blog post about the new "syscalls selection mechanisms", title etc TBD. We will have everything ready on time.

**Comment by jsalinas29** [comment]
@incertum let me know if you will have the blog ready for the April newsletter!
