### ISSUE TITLE
Discuss the automation of the release process

### ISSUE THREAD

**Issue by leodido** [falcosecurity/community#26]
**What type of proposal is this?**

/kind issue

I'd like to hear opinions about what I'm proposing into https://github.com/falcosecurity/falco/issues/726 about the release process for Falco.

**Comment by kris-nova** [comment]
I think @markyjackson-taulia is putting together a proposal for us here

**Comment by markyjackson-taulia** [comment]
Relates to https://github.com/falcosecurity/falco/issues/726

**Comment by leodido** [comment]
Discussion started in the 2019 July 25th office hours. Note [here](meeting-notes/2019-Jul-25.md).

Initial proposal (can be used as a starting point) is in [this comment](https://github.com/falcosecurity/falco/issues/726#issuecomment-515068046).

Discussion continued in the 2019 Sept 4th office hours. Notes [here](meeting-notes/2019-Sep-04.md).

Thanks @markyjackson-taulia  for taking care of it !
