### ISSUE TITLE
Discuss tagging of issues at next office hours

### ISSUE THREAD

**Issue by markjacksonfishing** [falcosecurity/community#35]
What type of proposal is this?

/kind issue

Details about the discussion:
Discuss tagging of issues (i.e. `good 1st issue`) for new comers and possible outreach (i.e. https://www.outreachy.org)

**Comment by leodido** [comment]
We have setup the Prow help plugin 2 days ago in this and other repos.

So we can tag issues using the following slash commands in order to apply or remove the `help wanted` and `good first issue` labels to an issue.

- /help
- /remove-help
- /good-first-issue
- /remove-good-first-issue
