### ISSUE TITLE
Discuss about running regression test cases on host

### ISSUE THREAD

**Issue by prankkelkar** [falcosecurity/community#37]
**What type of proposal is this?**

/kind debugging-hours

Issue: https://github.com/falcosecurity/falco/issues/798

**Details about the discussion**
Needed help in running test cases on host after build from source. Ill be available on 4th september from 9.00 am to 5.00pm IST .

**Comment by prankkelkar** [comment]
@leodido Please provide more details about the time slot so i can plan accordingly.

**Comment by leodido** [comment]
We've already identified that there is a bug thanks to your issue ([falco#798](https://github.com/falcosecurity/falco/issues/798)). As I proposed in that issue this sounds like a good first issue to submit a PR. Do you mind trying to submit a PR to fix it?

**Comment by mfdii** [comment]
@prankkelkar would you be able to join one of our weekly calls to discuss this issue more? https://github.com/falcosecurity/community

**Comment by prankkelkar** [comment]
Yes. Ill try to join. Just for the confirmation meeting timing are 8.30pm IST correct? Also do i need to do any other account or any other formality to join thia call?
