### ISSUE TITLE
Rebrand `office-hours` to `community`

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/community#38]
**What type of proposal is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind issue
> /kind pr
> /kind debugging-hours

Decided on the repo planning call, we would like this repositories scope to expand beyond office hours.

**Comment by fntlnz** [comment]
I like this idea, strongly +1

**Comment by leodido** [comment]
Strong +1 for me too
