### ISSUE TITLE
Standardized README.md files

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/community#51]
**What type of proposal is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind issue
> /kind pr
/kind debugging-hours

During the next office hours can we look at standardizing our `README.md` files?

Also should we look at re-writing some of these? Maybe on a live stream? Maybe at Kubecon? 

If we make it easy for people to find what they are looking for, we can drive adoption greatly.

**Comment by kris-nova** [comment]
https://github.com/falcosecurity/falcoctl/issues/9

**Comment by leodido** [comment]
agree +1

**Comment by fntlnz** [comment]
Related to https://github.com/falcosecurity/community/issues/53
