### ISSUE TITLE
#falco-triage Slack Channel and curators maintainer group

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/community#59]
**What type of proposal is this?**

/kind issue

**Details about the discussion**

I'd like to have a dedicated Slack channel where we can work solely on PR and issues triaging.

Q: What do you want want to achieve with this?
A: Our triaging process is automated via @poiana, that means that anyone in the community can start helping right now and do triaging via the slash `/` commands. However, not everyone has the same level of experience on the project. The purpose of this channel would be to create a group of people that discuss about triaging in Falco projects where they can cooperate on solving issues and merging PRs. 

However, if you read the title there's also the "curators maintainer group". That means that I expect the most active users interacting with the falco-triage slack channel to be promoted as Falco Maintainers with a "curator" role.

By "curator" I mean: a Falco Maintainer who is in charge of taking care of the project issues and knows the Falco community well enough to  them to the right people. Of course they can go and solve  themselves the ones that they can take care of.

Of course since the curator is a different role with different requirements we will also need to update the governance file accordingly: https://github.com/falcosecurity/falco/blob/dev/GOVERNANCE.md#maintainer-responsibilities

**Comment by kris-nova** [comment]
Related to #64 

I agree we need this - but we should maybe hold off on new channels until we cutover?
