### ISSUE TITLE
Cutover to CNCF Slack

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/community#64]
**What issue would you like to discuss?**

https://github.com/falcosecurity/falco/issues/983

Can we please cutover from the Sysdig slack to the CNCF slack?

In order to make this as seamless as possible we can use the slack feature: https://slack.com/resources/slack-for-admins/shared-channels-in-slack

> Please link the issue you would like to propose for discussion
>
> Issue #number

**Details about the discussion**

We need to understand which sub-channels (if any) we have.

Where do we discuss tools like `falcoctl` or the `prometheus-exporter`?

**Comment by leodido** [comment]
About the `falcoctl` and `falco-exporter` tools I would suggest dedicated channels in the CNCF slack, if possible.

And then add those channels in the org wide [SUPPORT.md](https://github.com/falcosecurity/.github/blob/master/SUPPORT.md#channels) like I did for the already existing channels.
