### ISSUE TITLE
Falco test cases are failing on ppc64le platform

### ISSUE THREAD

**Issue by sunil1783** [falcosecurity/community#66]
What type of proposal is this?
/kind issue

**What issue would you like to discuss?**
Build the Falco code on Ubuntu 18.04( kernel 4.15.0-66-generic) with eBPF flag enabled.
Following issues are facing :
- Not able to build falcosecurity/falco-builder docker image getting error as 
    "Cannot find a valid baseurl for repo: centos-sclo-sclo/ppc64le"
- Not able to build falcosecurity/falco:test docker image, As the "falco/docker/local/Dockerfile" downloads gcc-6/5 and binutils pre-built packages. So Docker package test case is failed.

> Issue
https://github.com/falcosecurity/falco/issues/982
PR
https://github.com/falcosecurity/falco/pull/932
 
**Details about the discussion**
- Need to port the dockerfiles to support ppc64le platform.
- Docker files should support latest OS having higher kernel versions with eBPF enabled. So we can 
  use latest versions of gcc and binutils instead of downloading pre-built packages.

**Comment by leodido** [comment]
Thanks for opening this @sunil1783.

I added this to the today's call agenda.
