### ISSUE TITLE
Missing call notes

### ISSUE THREAD

**Issue by leodido** [falcosecurity/community#91]
Hello friends,

this issue as a reminder that we miss the meeting notes and the recording of the following community calls:

- [x] 22th April 2020 (led by @kris-nova)
- [x] 29th April 2020 (led by @fntlnz)

/assign @fntlnz 
/assign @kris-nova

**Comment by fntlnz** [comment]
I've been working on the yesterda's in #92

**Comment by leodido** [comment]
- [ ] 13th May 2020 (led by @nibalizer)
